// Code generated by MockGen. DO NOT EDIT.
// Source: vault.go
//
// Generated by this command:
//
//	mockgen -source=vault.go -destination=mocks/vault_repository_mock.go -package=mocks VaultRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "credentials-vault/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVaultRepository is a mock of VaultRepository interface.
type MockVaultRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVaultRepositoryMockRecorder
	isgomock struct{}
}

// MockVaultRepositoryMockRecorder is the mock recorder for MockVaultRepository.
type MockVaultRepositoryMockRecorder struct {
	mock *MockVaultRepository
}

// NewMockVaultRepository creates a new mock instance.
func NewMockVaultRepository(ctrl *gomock.Controller) *MockVaultRepository {
	mock := &MockVaultRepository{ctrl: ctrl}
	mock.recorder = &MockVaultRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVaultRepository) EXPECT() *MockVaultRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVaultRepository) Create(ctx context.Context, item *domain.VaultItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVaultRepositoryMockRecorder) Create(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVaultRepository)(nil).Create), ctx, item)
}
