// Code generated by MockGen. DO NOT EDIT.
// Source: vault.go
//
// Generated by this command:
//
//	mockgen -source=vault.go -destination=mocks/vault_service_mock.go -package=mocks VaultService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "credentials-vault/internal/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockVaultService is a mock of VaultService interface.
type MockVaultService struct {
	ctrl     *gomock.Controller
	recorder *MockVaultServiceMockRecorder
	isgomock struct{}
}

// MockVaultServiceMockRecorder is the mock recorder for MockVaultService.
type MockVaultServiceMockRecorder struct {
	mock *MockVaultService
}

// NewMockVaultService creates a new mock instance.
func NewMockVaultService(ctrl *gomock.Controller) *MockVaultService {
	mock := &MockVaultService{ctrl: ctrl}
	mock.recorder = &MockVaultServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVaultService) EXPECT() *MockVaultServiceMockRecorder {
	return m.recorder
}

// CreateItem mocks base method.
func (m *MockVaultService) CreateItem(ctx context.Context, userID uuid.UUID, itemType domain.ItemType, encryptedData []byte, metadata map[string]string) (*domain.VaultItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", ctx, userID, itemType, encryptedData, metadata)
	ret0, _ := ret[0].(*domain.VaultItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateItem indicates an expected call of CreateItem.
func (mr *MockVaultServiceMockRecorder) CreateItem(ctx, userID, itemType, encryptedData, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockVaultService)(nil).CreateItem), ctx, userID, itemType, encryptedData, metadata)
}

// GetItem mocks base method.
func (m *MockVaultService) GetItem(ctx context.Context, id, userID uuid.UUID) (*domain.VaultItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", ctx, id, userID)
	ret0, _ := ret[0].(*domain.VaultItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockVaultServiceMockRecorder) GetItem(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockVaultService)(nil).GetItem), ctx, id, userID)
}

// ListItems mocks base method.
func (m *MockVaultService) ListItems(ctx context.Context, userID uuid.UUID, itemType *domain.ItemType) ([]*domain.VaultItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx, userID, itemType)
	ret0, _ := ret[0].([]*domain.VaultItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItems indicates an expected call of ListItems.
func (mr *MockVaultServiceMockRecorder) ListItems(ctx, userID, itemType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockVaultService)(nil).ListItems), ctx, userID, itemType)
}
