syntax = "proto3";

package credentials_vault.auth.v1;

option go_package = "credentials-vault/gen/go/auth/v1;authv1";

import "google/protobuf/timestamp.proto";

service AuthService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
}

message User {
  string id = 1;
  string username = 2;
  google.protobuf.Timestamp created_at = 3;
}

message RegisterRequest {
  string username = 1;
  string password = 2;
}

message RegisterResponse {
  User user = 1;
  string message = 2;
}

message LoginRequest {
  string username = 1;
  string password = 2;
}

message LoginResponse {
  User user = 1;
}